#! /bin/sh

bspc config border_width        2
bspc config window_gap         20

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc config focus_follows_mouse true
bspc config normal_border_color	none
bspc config auto_cancel 	true

bspc monitor eDP1 -d I II III
bspc monitor HDMI2 -d IV V VI

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#fix java apps (Intellij)
wmname LG3D
# fix multimonitor setups
~/.config/bspwm/window_layout.sh
# fix power settings
/usr/bin/xfce4-power-manager &
# Light locker on suspend
light-locker --lock-on-suspend &
# start the lemonbar
exec ~/.config/lemonbar/barconf.sh | lemonbar -p
